/**
 * OpenGPEX - An Open-source, Web-based Graphics and Photo editor.
 * Copyright (C) 2026 The OpenGPEX Authors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-3.0-only
 */

import { InteractionEvent, LocalRect, asWorldPoint } from '@opengpex/editor/core/types';

/**
 * InteractionMath: Interaction Helper Utilities
 * Unified handling of mathematical transformations and side-effect synchronization 
 * generated by interactions like dragging, scaling, and rotation.
 */
export const InteractionMath = {
  /**
   * calculateElasticRect: Elastic Boundary Scaling Operator
   * Encapsulates advanced logic for maintaining visual selection continuity 
   * by "pushing" the opposite edge when the mouse exceeds canvas boundaries.
   */
  calculateElasticRect(
    e: InteractionEvent, 
    params: {
      curX: number;
      curY: number;
      startAnchor: { x: number; y: number };
      startBox: { w: number; h: number };
      aspect?: number;
      resizeType: string;
      canvasDim: { w: number; h: number };
      maxPush: { x: number; y: number };
    }
  ): LocalRect {
    const { curX, curY, startAnchor, startBox, aspect, resizeType, canvasDim, maxPush } = params;
    const g = e.geometry;

    // 1. Get boundary constraint point and raw push vector (dx/dy)
    const { x: fX, y: fY, dx, dy } = g.space.clampPointToRect({ x: curX, y: curY }, canvasDim);

    // 2. Update historical maximum push (ensures elastic smoothness on pull-back)
    if (Math.abs(dx) > Math.abs(maxPush.x)) maxPush.x = dx;
    if (Math.abs(dy) > Math.abs(maxPush.y)) maxPush.y = dy;

    let ep = { x: maxPush.x * 2, y: maxPush.y * 2 };

    // 3. Proportional push balance: If aspect ratio is locked, balance the push vector
    if (aspect) {
      // Determine logical direction based on handle type (e.g., 'se' is +x, +y)
      const dir = { 
        x: resizeType.includes('w') ? -1 : 1, 
        y: resizeType.includes('n') ? -1 : 1 
      };
      const balanced = g.space.balanceVectorByAspect({ x: maxPush.x, y: maxPush.y }, aspect, dir);
      ep = { x: balanced.x * 2, y: balanced.y * 2 };
    }

    // 4. Generate dynamic anchor and execute core scaling algorithm
    const dynAnchor = g.space.clampPointToRect({ x: startAnchor.x - ep.x, y: startAnchor.y - ep.y }, canvasDim);
    
    const next = g.asLocalRect(g.space.calculateResizedRect(
      asWorldPoint({ x: fX, y: fY }), 
      asWorldPoint(dynAnchor), 
      aspect, 
      resizeType, 
      startBox
    ));

    // 5. Apply final physical boundary constraints
    return g.space.clampRectWithAspect(next, canvasDim, asWorldPoint(dynAnchor), aspect) as LocalRect;
  },

  /**
   * getCanvasDelta: Calculate displacement in Canvas-space (Immune to Zoom/Pan drift)
   */
  getCanvasDelta(e: InteractionEvent, startCanvas: { x: number; y: number }) {
    return {
      dx: e.point.canvas.x - startCanvas.x,
      dy: e.point.canvas.y - startCanvas.y
    };
  },

  /**
   * snapAndSync: Perform snapping and sync guides (With built-in throttling)
   * 
   * @param e         Interaction event
   * @param rect      Current raw calculated rectangle
   * @param state     Throttling state (should be persisted in Handler)
   * @param options   Snap configuration
   */
  snapAndSync(
    e: InteractionEvent,
    rect: { x: number; y: number; w: number; h: number },
    state: { lastThrottleTime: number },
    options: { clamp?: boolean; throttleMs?: number; excludeLayerId?: string } = {}
  ): LocalRect {
    const isSnapping = e.state.interaction.isSnapping;
    const frame = e.activeFrame;

    if (!isSnapping) {
      // If snapping is disabled, clear guides but still respect clamping if requested
      e.actions.fast.setTransient('smartguides', null);
      
      if (options.clamp) {
        const clamped = e.geometry.snapping.snapRect(rect, frame, { 
          clamp: true,
          // By providing an empty target or a flag, we ensure only clamping happens
          // In our geometry engine, snapRect with snapping disabled or no guides found will still clamp if requested.
        });
        return e.geometry.asLocalRect({ ...rect, x: clamped.x, y: clamped.y });
      }
      
      return e.geometry.asLocalRect(rect);
    }

    const snapped = e.geometry.snapping.snapRect(rect, frame, { 
      clamp: options.clamp,
      excludeLayerId: options.excludeLayerId 
    });

    // Throttle guide distribution (sync to fast-track transient)
    const now = Date.now();
    if (now - state.lastThrottleTime >= (options.throttleMs || 16)) {
      e.actions.fast.setTransient('smartguides', snapped.smartguides);
      state.lastThrottleTime = now;
    }

    // Return snapped local coordinate rectangle
    return e.geometry.asLocalRect({ ...rect, x: snapped.x, y: snapped.y });
  },

  /**
   * calculateDragPosition: Calculate new position after dragging (Legacy support)
   */
  calculateDragPosition(
    currentMouse: { x: number; y: number },
    startMouse: { x: number; y: number },
    startValue: { x: number; y: number },
    scale: number
  ) {
    const dx = (currentMouse.x - startMouse.x) / scale;
    const dy = (currentMouse.y - startMouse.y) / scale;

    return {
      x: startValue.x + dx,
      y: startValue.y + dy
    };
  },

  /**
   * isStaticClick: Determine if the interaction is a static click (no significant movement).
   */
  isStaticClick(e: InteractionEvent, startCanvas: { x: number; y: number }, threshold = 5): boolean {
    const { dx, dy } = InteractionMath.getCanvasDelta(e, startCanvas);
    return Math.sqrt(dx * dx + dy * dy) < threshold;
  },

  /**
   * isDoubleClick: Determine if the interaction is a double click.
   */
  isDoubleClick(e: InteractionEvent, startCanvas: { x: number; y: number }, threshold = 5): boolean {
    return InteractionMath.isStaticClick(e, startCanvas, threshold) && 
           (e.nativeEvent as MouseEvent).detail === 2;
  },

  /**
   * alignToPhysicalPixels: Core alignment engine (force snap to physical pixels)
   * 
   * @param targetLayerId If provided, align to the physical pixel grid of this layer; otherwise align to canvas integer grid.
   */
  alignToPhysicalPixels(e: InteractionEvent, rect: LocalRect, targetLayerId: string): LocalRect {
    const frame = e.activeFrame;
    const g = e.geometry;

    const activeLayer = targetLayerId ? frame.layers.byId[targetLayerId] : undefined;
    if (!activeLayer || activeLayer.type !== 'image') return rect;

    // Get transform matrix from canvas space to layer physical space
    const M_layer = g.transform.getLayerLocalMatrix(activeLayer, frame);
    const M_inv = M_layer.inverse();

    // Transform key four points of rect to layer-local space
    const tl = M_inv.apply({ x: rect.x, y: rect.y });
    const br = M_inv.apply({ x: rect.x + rect.w, y: rect.y + rect.h });

    // Perform precise alignment in layer physical pixel space
    const snappedTl = { x: Math.round(tl.x), y: Math.round(tl.y) };
    const snappedBr = { x: Math.round(br.x), y: Math.round(br.y) };

    // Map aligned coordinates back to canvas space
    const finalTl = M_layer.apply(snappedTl);
    const finalBr = M_layer.apply(snappedBr);

    return {
      ...rect,
      x: finalTl.x,
      y: finalTl.y,
      w: finalBr.x - finalTl.x,
      h: finalBr.y - finalTl.y
    } as LocalRect;
  },

};
