/**
 * OpenGPEX - An Open-source, Web-based Graphics and Photo editor.
 * Copyright (C) 2026 The OpenGPEX Authors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-3.0-only
 */

import { InteractionEvent, LocalRect, asWorldPoint } from '@opengpex/editor/core/types';
import type { SnapFilterOptions } from '@opengpex/editor/core/geometry/operators/snapping';

/**
 * InteractionMath: Interaction Helper Utilities
 * Unified handling of mathematical transformations and side-effect synchronization 
 * generated by interactions like dragging, scaling, and rotation.
 */
export const InteractionMath = {
  /**
   * calculateClampedRect: Standard clamped resize (Photoshop-style).
   *
   * The cursor is clamped to canvas bounds and the anchor stays fixed.
   * No "elastic push" — the opposite edge never moves unless the user
   * explicitly drags it. This matches the universal mental model of
   * anchor-based resize in Photoshop, GIMP, Affinity, and Krita.
   *
   * @deprecated The `maxPush` parameter is retained for interface
   * compatibility but ignored. It will be removed in a future cleanup.
   */
  calculateElasticRect(
    e: InteractionEvent, 
    params: {
      curX: number;
      curY: number;
      startAnchor: { x: number; y: number };
      startBox: { w: number; h: number };
      aspect?: number;
      resizeType: string;
      canvasDim: { w: number; h: number };
      maxPush: { x: number; y: number };
    }
  ): LocalRect {
    const { curX, curY, startAnchor, aspect, resizeType, canvasDim } = params;
    const g = e.geometry;

    // 1. Clamp cursor to canvas bounds (anchor stays fixed)
    const { x: clampedX, y: clampedY } = g.space.clampPointToRect({ x: curX, y: curY }, canvasDim);

    // 2. Standard resize: fixed anchor + clamped cursor → rect
    const rawRect = g.asLocalRect(g.space.calculateResizedRect(
      asWorldPoint({ x: clampedX, y: clampedY }),
      asWorldPoint(startAnchor),
      aspect,
      resizeType,
      params.startBox
    ));

    // 3. Final boundary clamp: ensure rect stays within canvas, respecting aspect
    return g.space.clampRectWithAspect(rawRect, canvasDim, asWorldPoint(startAnchor), aspect) as LocalRect;
  },

  /**
   * getCanvasDelta: Calculate displacement in Canvas-space (Immune to Zoom/Pan drift)
   */
  getCanvasDelta(e: InteractionEvent, startCanvas: { x: number; y: number }) {
    return {
      dx: e.point.canvas.x - startCanvas.x,
      dy: e.point.canvas.y - startCanvas.y
    };
  },

  /**
   * snapAndSync: Perform snapping and sync guides (With built-in throttling)
   * 
   * @param e         Interaction event
   * @param rect      Current raw calculated rectangle
   * @param state     Throttling state (should be persisted in Handler)
   * @param options   Snap configuration
   */
  snapAndSync(
    e: InteractionEvent,
    rect: { x: number; y: number; w: number; h: number },
    state: { lastThrottleTime: number },
    options: { clamp?: boolean; throttleMs?: number; excludeLayerId?: string } = {}
  ): LocalRect {
    const isSnapping = e.state.interaction.isSnapping;
    const frame = e.activeFrame;

    // Read SmartGuides plugin config for fine-grained filtering
    const sgConfig = e.state.pluginConfig?.['opengpex.overlays.smart_guides'] as Record<string, unknown> | undefined;
    const filterOptions: SnapFilterOptions = sgConfig ? {
      snapToCanvas: sgConfig.snapToCanvas as boolean | undefined,
      snapToBirth: sgConfig.snapToBirth as boolean | undefined,
      snapToLayers: sgConfig.snapToLayers as boolean | undefined,
      excludeLayerTypes: sgConfig.excludeLayerTypes as string[] | undefined,
      ignoreLockedLayers: sgConfig.ignoreLockedLayers as boolean | undefined,
      ignoreSmallLayers: sgConfig.ignoreSmallLayers as boolean | undefined,
      smallLayerThreshold: sgConfig.smallLayerThreshold as number | undefined,
      maxSnapTargets: sgConfig.maxSnapTargets as number | undefined,
    } : {};

    if (!isSnapping) {
      // If snapping is disabled, clear guides but still respect clamping if requested
      e.actions.fast.setTransient('smartguides', null);
      
      if (options.clamp) {
        const clamped = e.geometry.snapping.snapRect(rect, frame, { 
          clamp: true,
          // By providing an empty target or a flag, we ensure only clamping happens
          // In our geometry engine, snapRect with snapping disabled or no guides found will still clamp if requested.
        });
        return e.geometry.asLocalRect({ ...rect, x: clamped.x, y: clamped.y });
      }
      
      return e.geometry.asLocalRect(rect);
    }

    const snapped = e.geometry.snapping.snapRect(rect, frame, { 
      clamp: options.clamp,
      excludeLayerId: options.excludeLayerId,
      ...filterOptions
    });

    // Throttle guide distribution (sync to fast-track transient)
    const now = Date.now();
    if (now - state.lastThrottleTime >= (options.throttleMs || 16)) {
      e.actions.fast.setTransient('smartguides', snapped.smartguides);
      state.lastThrottleTime = now;
    }

    // Return snapped local coordinate rectangle
    return e.geometry.asLocalRect({ ...rect, x: snapped.x, y: snapped.y });
  },

  /**
   * calculateDragPosition: Calculate new position after dragging (Legacy support)
   */
  calculateDragPosition(
    currentMouse: { x: number; y: number },
    startMouse: { x: number; y: number },
    startValue: { x: number; y: number },
    scale: number
  ) {
    const dx = (currentMouse.x - startMouse.x) / scale;
    const dy = (currentMouse.y - startMouse.y) / scale;

    return {
      x: startValue.x + dx,
      y: startValue.y + dy
    };
  },

  /**
   * isStaticClick: Determine if the interaction is a static click (no significant movement).
   */
  isStaticClick(e: InteractionEvent, startCanvas: { x: number; y: number }, threshold = 5): boolean {
    const { dx, dy } = InteractionMath.getCanvasDelta(e, startCanvas);
    return Math.sqrt(dx * dx + dy * dy) < threshold;
  },

  /**
   * isDoubleClick: Determine if the interaction is a double click.
   */
  isDoubleClick(e: InteractionEvent, startCanvas: { x: number; y: number }, threshold = 5): boolean {
    return InteractionMath.isStaticClick(e, startCanvas, threshold) && 
           (e.nativeEvent as MouseEvent).detail === 2;
  },

  /**
   * alignToPhysicalPixels: Core alignment engine (force snap to physical pixels)
   * 
   * @param targetLayerId If provided, align to the physical pixel grid of this layer; otherwise align to canvas integer grid.
   */
  alignToPhysicalPixels(e: InteractionEvent, rect: LocalRect, targetLayerId: string): LocalRect {
    const frame = e.activeFrame;
    const g = e.geometry;

    const activeLayer = targetLayerId ? frame.layers.byId[targetLayerId] : undefined;
    if (!activeLayer || activeLayer.type !== 'image') return rect;

    // Get transform matrix from canvas space to layer physical space
    const M_layer = g.transform.getLayerLocalMatrix(activeLayer, frame);
    const M_inv = M_layer.inverse();

    // Transform key four points of rect to layer-local space
    const tl = M_inv.apply({ x: rect.x, y: rect.y });
    const br = M_inv.apply({ x: rect.x + rect.w, y: rect.y + rect.h });

    // Perform precise alignment in layer physical pixel space
    const snappedTl = { x: Math.round(tl.x), y: Math.round(tl.y) };
    const snappedBr = { x: Math.round(br.x), y: Math.round(br.y) };

    // Map aligned coordinates back to canvas space
    const finalTl = M_layer.apply(snappedTl);
    const finalBr = M_layer.apply(snappedBr);

    return {
      ...rect,
      x: finalTl.x,
      y: finalTl.y,
      w: finalBr.x - finalTl.x,
      h: finalBr.y - finalTl.y
    } as LocalRect;
  },

};
