/**
 * OpenGPEX - An Open-source, Web-based Graphics and Photo editor.
 * Copyright (C) 2026 The OpenGPEX Authors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-3.0-only
 */

import { InteractionEvent, LocalRect, asWorldPoint } from '@opengpex/editor/core/types';
import type { SnapFilterOptions } from '@opengpex/editor/core/geometry/operators/snapping';
import { presets } from '@opengpex/editor/core/helpers/preferences';

/** Resolved at call time from PresetsFactory (allows runtime override via Settings UI). */
const getStaticThreshold = () => presets.get('STATIC_CLICK_THRESHOLD');

/**
 * Snap operation state tracking for velocity escape and sticky guide hysteresis.
 */
export interface SnapOpState {
  lastThrottleTime: number;
  lastPointerPos?: { x: number; y: number; time: number };
  /**
   * Low-pass filtered pointer speed (screen px/ms). Raw per-event speed is too
   * noisy to gate snapping directly — see snapAndSync for why it's smoothed.
   */
  lastSmoothedSpeed?: number;
  lastGuideX?: number;
  lastGuideY?: number;
}

/**
 * InteractionMath: Interaction Helper Utilities
 * Unified handling of mathematical transformations and side-effect synchronization 
 * generated by interactions like dragging, scaling, and rotation.
 */
export const InteractionMath = {
  /**
   * calculateClampedRect: Standard clamped resize (Photoshop-style).
   *
   * The cursor is clamped to canvas bounds and the anchor stays fixed.
   * No "elastic push" — the opposite edge never moves unless the user
   * explicitly drags it. This matches the universal mental model of
   * anchor-based resize in Photoshop, GIMP, Affinity, and Krita.
   *
   * @deprecated The `maxPush` parameter is retained for interface
   * compatibility but ignored. It will be removed in a future cleanup.
   */
  calculateElasticRect(
    e: InteractionEvent, 
    params: {
      curX: number;
      curY: number;
      startAnchor: { x: number; y: number };
      startBox: { w: number; h: number };
      aspect?: number;
      resizeType: string;
      canvasDim: { w: number; h: number };
      maxPush: { x: number; y: number };
    }
  ): LocalRect {
    const { curX, curY, startAnchor, aspect, resizeType, canvasDim } = params;
    const g = e.geometry;

    // 1. Clamp cursor to canvas bounds (anchor stays fixed)
    const { x: clampedX, y: clampedY } = g.space.clampPointToRect({ x: curX, y: curY }, canvasDim);

    // 2. Standard resize: fixed anchor + clamped cursor → rect
    const rawRect = g.asLocalRect(g.space.calculateResizedRect(
      asWorldPoint({ x: clampedX, y: clampedY }),
      asWorldPoint(startAnchor),
      aspect,
      resizeType,
      params.startBox
    ));

    // 3. Final boundary clamp: ensure rect stays within canvas, respecting aspect
    return g.space.clampRectWithAspect(rawRect, canvasDim, asWorldPoint(startAnchor), aspect) as LocalRect;
  },

  /**
   * getCanvasDelta: Calculate displacement in Canvas-space (Immune to Zoom/Pan drift)
   */
  getCanvasDelta(e: InteractionEvent, startCanvas: { x: number; y: number }) {
    return {
      dx: e.point.canvas.x - startCanvas.x,
      dy: e.point.canvas.y - startCanvas.y
    };
  },

  /**
   * isSnapSuppressed: Global drag-time modifier check.
   *
   * Holding Shift or Alt/Option during a drag temporarily bypasses smart guides
   * (mirrors the Figma/Photoshop "hold-to-bypass snapping" convention). This is
   * evaluated on every pointer event, so releasing the key restores snapping
   * and guide rendering immediately — no persistent state to manage.
   *
   * Note: Alt is the "clean" bypass key. Shift additionally carries gesture
   * semantics elsewhere (aspect-ratio lock in resize, 45° arrow snap, 15°
   * rotation snap), so Shift+drag disables guides AND those behaviours fire.
   */
  isSnapSuppressed(e: InteractionEvent): boolean {
    return e.keys.shift || e.keys.alt;
  },

  /**
   * snapAndSync: Perform snapping and sync guides (With velocity escape & sticky hysteresis)
   * 
   * @param e         Interaction event
   * @param rect      Current raw calculated rectangle
   * @param state     Persistent operation state
   * @param options   Snap configuration
   */
  snapAndSync(
    e: InteractionEvent,
    rect: { x: number; y: number; w: number; h: number },
    state: SnapOpState,
    options: { clamp?: boolean; throttleMs?: number; excludeLayerId?: string } = {}
  ): LocalRect {
    const isSnapping = presets.get('SNAP_ENABLED') && !InteractionMath.isSnapSuppressed(e);
    const frame = e.activeFrame;

    // ── 1. Velocity escape detection (Photoshop-like escape velocity) ──
    const now = Date.now();
    const baseThreshold = presets.get('SNAP_THRESHOLD') ?? 6;
    let velocityFactor = 1.0;

    if (state.lastPointerPos) {
      const dt = now - state.lastPointerPos.time;
      if (dt > 0 && dt < 250) {
        const dx = e.point.screen.x - state.lastPointerPos.x;
        const dy = e.point.screen.y - state.lastPointerPos.y;
        const rawSpeed = Math.hypot(dx, dy) / dt; // screen px / ms

        // Low-pass the raw per-event speed before using it to gate snapping.
        // Pointer events fire with jittery gaps (1-2ms bursts, coalesced frames,
        // occasional long stalls), so a single noisy sample can momentarily spike
        // above V_MAX and kill snapping — the guide blinks and the layer briefly
        // un-sticks mid-drag even while the user is dragging steadily.
        //
        // A time-constant EMA normalizes for the irregular dt: alpha grows with
        // the gap, so densely-fired events are smoothed heavily while a sample
        // after a long gap is trusted more. TAU is the perceptual smoothing
        // window — small enough that a genuine fast fling still crosses V_MAX
        // within ~1 frame, large enough to swallow per-event noise.
        const TAU = 45; // ms
        const alpha = 1 - Math.exp(-dt / TAU);
        const speed = state.lastSmoothedSpeed === undefined
          ? rawSpeed
          : state.lastSmoothedSpeed + alpha * (rawSpeed - state.lastSmoothedSpeed);
        state.lastSmoothedSpeed = speed;

        // Escape velocity curve:
        // <= 0.25 px/ms (~15px/frame @ 60Hz): Fine positioning -> 100% threshold
        // >= 0.85 px/ms (~50px/frame @ 60Hz): Fast glide -> 0% threshold (free movement)
        const V_MIN = 0.25;
        const V_MAX = 0.85;
        if (speed >= V_MAX) {
          velocityFactor = 0;
        } else if (speed > V_MIN) {
          velocityFactor = 1 - (speed - V_MIN) / (V_MAX - V_MIN);
        }
      }
    } else {
      // First sample of a fresh gesture: drop any smoothed speed left over from a
      // previous drag so the new gesture starts from a clean slate.
      state.lastSmoothedSpeed = undefined;
    }
    state.lastPointerPos = { x: e.point.screen.x, y: e.point.screen.y, time: now };

    // ── 2. Bypass snapping if suppressed or high speed ──
    if (!isSnapping || velocityFactor <= 0.05) {
      e.actions.fast.setTransient('smartguides', null);
      state.lastGuideX = undefined;
      state.lastGuideY = undefined;

      if (options.clamp) {
        const clamped = e.geometry.snapping.snapRect(rect, frame, { 
          clamp: true,
          snapToCanvas: false,
          snapToBirth: false,
          snapToLayers: false,
        });
        return e.geometry.asLocalRect({ ...rect, x: clamped.x, y: clamped.y });
      }

      return e.geometry.asLocalRect(rect);
    }

    // ── 3. Read snap filter options from PresetsFactory ──
    const filterOptions: SnapFilterOptions = {
      snapToCanvas: presets.get('SNAP_TO_CANVAS'),
      snapToBirth: presets.get('SNAP_TO_BIRTH'),
      snapToLayers: presets.get('SNAP_TO_LAYERS'),
      excludeLayerTypes: presets.get('SNAP_EXCLUDE_LAYER_TYPES'),
      ignoreLockedLayers: presets.get('SNAP_IGNORE_LOCKED_LAYERS'),
      ignoreSmallLayers: presets.get('SNAP_IGNORE_SMALL_LAYERS'),
      smallLayerThreshold: presets.get('SNAP_SMALL_LAYER_THRESHOLD'),
      maxSnapTargets: presets.get('SNAP_MAX_TARGETS'),
      lastGuideX: state.lastGuideX,
      lastGuideY: state.lastGuideY,
    };

    const effectiveThreshold = baseThreshold * velocityFactor;
    const snapped = e.geometry.snapping.snapRect(rect, frame, { 
      clamp: options.clamp,
      threshold: effectiveThreshold,
      excludeLayerId: options.excludeLayerId,
      ...filterOptions
    });

    // Update sticky guide tracking
    state.lastGuideX = snapped.smartguides?.x;
    state.lastGuideY = snapped.smartguides?.y;

    // Distribute guide sync
    if (now - state.lastThrottleTime >= (options.throttleMs || 16)) {
      e.actions.fast.setTransient('smartguides', snapped.smartguides);
      state.lastThrottleTime = now;
    }

    // Return snapped local coordinate rectangle
    return e.geometry.asLocalRect({ ...rect, x: snapped.x, y: snapped.y });
  },

  /**
   * calculateDragPosition: Calculate new position after dragging (Legacy support)
   */
  calculateDragPosition(
    currentMouse: { x: number; y: number },
    startMouse: { x: number; y: number },
    startValue: { x: number; y: number },
    scale: number
  ) {
    const dx = (currentMouse.x - startMouse.x) / scale;
    const dy = (currentMouse.y - startMouse.y) / scale;

    return {
      x: startValue.x + dx,
      y: startValue.y + dy
    };
  },

  /**
   * isStaticClick: Determine if the interaction is a static click (no significant movement).
   *
   * Default threshold sourced from `STATIC_CLICK_THRESHOLD` preset (2px).
   * Callers may override for specific use cases.
   */
  isStaticClick(e: InteractionEvent, startCanvas: { x: number; y: number }, threshold?: number): boolean {
    const t = threshold ?? getStaticThreshold();
    const { dx, dy } = InteractionMath.getCanvasDelta(e, startCanvas);
    return Math.sqrt(dx * dx + dy * dy) < t;
  },

  /**
   * isDoubleClick: Determine if the interaction is a double click.
   */
  isDoubleClick(e: InteractionEvent, startCanvas: { x: number; y: number }, threshold?: number): boolean {
    return InteractionMath.isStaticClick(e, startCanvas, threshold) && 
           (e.nativeEvent as MouseEvent).detail === 2;
  },

  /**
   * alignToPhysicalPixels: Core alignment engine (force snap to physical pixels)
   * 
   * @param targetLayerId If provided, align to the physical pixel grid of this layer; otherwise align to canvas integer grid.
   */
  alignToPhysicalPixels(e: InteractionEvent, rect: LocalRect, targetLayerId: string): LocalRect {
    const frame = e.activeFrame;
    const g = e.geometry;

    const activeLayer = targetLayerId ? frame.layers.byId[targetLayerId] : undefined;
    if (!activeLayer || activeLayer.type !== 'image') return rect;

    // Get transform matrix from canvas space to layer physical space
    const M_layer = g.transform.getLayerLocalMatrix(activeLayer, frame);
    const M_inv = M_layer.inverse();

    // Transform key four points of rect to layer-local space
    const tl = M_inv.apply({ x: rect.x, y: rect.y });
    const br = M_inv.apply({ x: rect.x + rect.w, y: rect.y + rect.h });

    // Perform precise alignment in layer physical pixel space
    const snappedTl = { x: Math.round(tl.x), y: Math.round(tl.y) };
    const snappedBr = { x: Math.round(br.x), y: Math.round(br.y) };

    // Map aligned coordinates back to canvas space
    const finalTl = M_layer.apply(snappedTl);
    const finalBr = M_layer.apply(snappedBr);

    return {
      ...rect,
      x: finalTl.x,
      y: finalTl.y,
      w: finalBr.x - finalTl.x,
      h: finalBr.y - finalTl.y
    } as LocalRect;
  },

};
