// scripts/scan-plugins.mjs
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Manually construct __dirname under ESM mode
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 1. Base path configuration
const BASE_PLUGINS_DIR = path.join(__dirname, '../src/lib/opengpex/plugins');
const TARGET_REGISTRY_USER_PATH = path.join(BASE_PLUGINS_DIR, 'registry-user.ts');
const USER_PLUGINS_DIR = path.join(BASE_PLUGINS_DIR, 'user');

// Ensure user directory exists
if (!fs.existsSync(USER_PLUGINS_DIR)) {
  fs.mkdirSync(USER_PLUGINS_DIR, { recursive: true });
}

// Physically clear registry-user.ts in preparation for overwrite write
if (fs.existsSync(TARGET_REGISTRY_USER_PATH)) {
  fs.unlinkSync(TARGET_REGISTRY_USER_PATH);
}

// 2. Recursively find deepest plugin directories containing index.ts or index.tsx (restricted to user directory)
function findPlugins(dir) {
  let plugins = [];
  if (!fs.existsSync(dir)) return plugins;
  
  const items = fs.readdirSync(dir);
  for (const item of items) {
    const fullPath = path.join(dir, item);
    if (fs.statSync(fullPath).isDirectory()) {
      if (fs.existsSync(path.join(fullPath, 'index.ts')) || fs.existsSync(path.join(fullPath, 'index.tsx'))) {
        plugins.push(fullPath);
      } else {
        plugins = plugins.concat(findPlugins(fullPath));
      }
    }
  }
  return plugins;
}

const userPluginDirs = findPlugins(USER_PLUGINS_DIR);
const importStatements = [];
const registryEntries = [];

userPluginDirs.forEach(folderPath => {
  const relativePath = path.relative(BASE_PLUGINS_DIR, folderPath);

  // Construct a unique variable alias and unify cross-platform path separators (Forward Slashes)
  const camelCaseName = relativePath.replace(/[^a-zA-Z0-9]/g, '_');
  const importAlias = `plugin_${camelCaseName}`;
  
  // Convert Windows backslashes \\ to standard web slashes /
  const importPath = `./${relativePath.split(path.sep).join('/')}`;
  
  importStatements.push(`import { plugin as ${importAlias} } from '${importPath}';`);
  
  const folderName = path.basename(folderPath);
  registryEntries.push(`  {
    ...${importAlias},
    sourceType: 'user',
    _folderName: '${folderName}'
  }`);
});

// 6. Construct the registry-user.ts template for overwrite writing
const importSection = importStatements.length > 0 ? importStatements.join('\n') + '\n' : '';
const registryTemplate = `/**
 * ⚠️  [Auto-generated by scan-plugins.mjs]
 * Do not modify this file manually.
 * Run "pnpm scan-plugins" to refresh this user-space registry.
 */

${importSection}
export const PLUGINS = [
${registryEntries.join(',\n')}
];

export default PLUGINS;
`;

// Write to the target registry file
fs.writeFileSync(TARGET_REGISTRY_USER_PATH, registryTemplate, 'utf-8');
console.log(`\n✨ [OpenGPEX] User registry-user.ts generated successfully! Scanned ${registryEntries.length} user-space plugins.`);
console.log(`📁 Target file: src/lib/opengpex/plugins/registry-user.ts\n`);