// scripts/sync-plugins.mjs
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 1. Base path configuration
const BASE_PLUGINS_DIR = path.join(__dirname, '../src/lib/opengpex/plugins');
const CORE_PLUGIN_DIR = path.join(__dirname, '../src/lib/opengpex/core/plugin');
const TARGET_REGISTRY_PATH = path.join(CORE_PLUGIN_DIR, 'registry.ts');

const TARGET_DIRS = {
  base: path.join(BASE_PLUGINS_DIR, 'base'),
  community: path.join(BASE_PLUGINS_DIR, 'community')
};

// Release Guard: Ensure user plugins directory is empty (official releases must not bundle any user plugins)
// Active only when the --release flag is provided (used during pnpm build:release)
const isReleaseMode = process.argv.includes('--release');
const USER_PLUGINS_DIR = path.join(BASE_PLUGINS_DIR, 'user');
if (isReleaseMode && fs.existsSync(USER_PLUGINS_DIR)) {
  const userEntries = fs.readdirSync(USER_PLUGINS_DIR).filter(
    name => !name.startsWith('.') && name !== 'README.md'
  );
  if (userEntries.length > 0) {
    console.error('\n❌ [OpenGPEX Release Guard] plugins/user/ directory is NOT empty!');
    console.error(`   Found: ${userEntries.join(', ')}`);
    console.error('   For official releases, the user plugin directory must be clean.');
    console.error('   Please move or remove all user plugins before building a release.\n');
    process.exit(1);
  }
}

// Ensure core plugin registry directory exists
if (!fs.existsSync(CORE_PLUGIN_DIR)) {
  fs.mkdirSync(CORE_PLUGIN_DIR, { recursive: true });
}

// Physically delete old registry file
if (fs.existsSync(TARGET_REGISTRY_PATH)) {
  fs.unlinkSync(TARGET_REGISTRY_PATH);
}

const importStatements = [];
const registryEntries = [];

// Recursively find the deepest plugin directories containing index.ts or index.tsx
function findPlugins(dir) {
  let plugins = [];
  if (!fs.existsSync(dir)) return plugins;
  
  const items = fs.readdirSync(dir);
  for (const item of items) {
    const fullPath = path.join(dir, item);
    if (fs.statSync(fullPath).isDirectory()) {
      if (fs.existsSync(path.join(fullPath, 'index.ts')) || fs.existsSync(path.join(fullPath, 'index.tsx'))) {
        plugins.push(fullPath);
      } else {
        plugins = plugins.concat(findPlugins(fullPath));
      }
    }
  }
  return plugins;
}

Object.entries(TARGET_DIRS).forEach(([sourceType, dirPath]) => {
  const pluginDirs = findPlugins(dirPath);
  
  pluginDirs.forEach(folderPath => {
    const relativePath = path.relative(BASE_PLUGINS_DIR, folderPath);
    
    // Construct a unique variable alias and unify cross-platform path separators (Forward Slashes)
    const camelCaseName = relativePath.replace(/[^a-zA-Z0-9]/g, '_');
    const importAlias = `plugin_${camelCaseName}`;
    
    // Reference official plugins in plugins/ from core/plugin/registry.ts, relative path must start with ../../plugins/
    const importPath = `../../plugins/${relativePath.split(path.sep).join('/')}`;
    
    importStatements.push(`import { plugin as ${importAlias} } from '${importPath}';`);

    registryEntries.push(`  {
    ...${importAlias},
    sourceType: '${sourceType}'
  }`);
  });
});

// Template interpolation to generate the complete core registry.ts
const registryTemplate = `/**
 * ⚠️  [Auto-generated by sync-plugins.mjs]
 * Do not modify this file manually.
 * Run "pnpm sync-plugins" to refresh this core registry.
 */

${importStatements.join('\n')}

export const PLUGINS = [
${registryEntries.join(',\n')}
];

export default PLUGINS;
`;

// Write the core registry template to the target file
fs.writeFileSync(TARGET_REGISTRY_PATH, registryTemplate, 'utf-8');
console.log(`\n✨ [OpenGPEX Sync] Core registry.ts regenerated successfully! Synced ${registryEntries.length} official core plugins.`);
console.log(`📁 Target file: src/lib/opengpex/core/plugin/registry.ts\n`);
