/**
 * OpenGPEX - An Open-source, Web-based Graphics and Photo editor.
 * Copyright (C) 2026 The OpenGPEX Authors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-3.0-only
 */

import { GeometryService, PixelService, AssetService, LayerService, LayerUpdateTx, LayerEditor, asLocalShape, asLocalRect, asWorldShape, EditorActions, EditorData, Layer, VectorMask, BitmapMask, isPolygon, LocalShape, LocalPolygon } from '@opengpex/editor/core/types';
import { polygonToShape } from '@opengpex/editor/core/helpers/path2d';
import { LayerFactory } from './LayerFactory';

/** Business convention: ID feature of hole masks generated by peeling */
// const MASK_ID_PEEL_HOLE = 'mask-peel-hole';

export function createLayerService(
  geometry: GeometryService,
  pixels: PixelService,
  assets: AssetService,
  actions: EditorActions,
  getState: () => EditorData
): LayerService {
  return {
    ...LayerFactory,

    updateLayer: (frameId, runner) => {
      const state = getState();
      const frame = state.frames.byId[frameId];
      if (!frame) return;

      const patches: Record<string, Partial<Layer>> = {};

      const tx: LayerUpdateTx = {
        edit: (layerId) => {
          const layer = frame.layers.byId[layerId];
          if (!layer) {
            console.warn(`[LayerTx] Layer ${layerId} not found in frame ${frameId}`);
          }

          // 🌟 Initialize vectorMasks in draft to avoid duplicate fallbacks later
          if (!patches[layerId]) {
            patches[layerId] = {};
          }
          if (patches[layerId].vectorMasks === undefined) {
            patches[layerId].vectorMasks = layer?.vectorMasks || [];
          }

          const editor: LayerEditor = {
            setAsset: (asset) => {
              patches[layerId] = { ...patches[layerId], src: asset.url, assetId: asset.id };
              return editor;
            },
            setShape: (shape) => {
              patches[layerId] = { ...patches[layerId], ...shape };
              return editor;
            },
            removeMask: (pattern) => {
              const currentMasks = patches[layerId].vectorMasks || [];
              const newMasks = currentMasks.filter((m: VectorMask) => !m.id.includes(pattern));
              patches[layerId].vectorMasks = newMasks;
              return editor;
            },
            applyMask: (shape, inverted = false) => {
              const currentMasks = patches[layerId].vectorMasks || [];
              const newMask = LayerFactory.getNewVectorMask(shape, inverted);
              patches[layerId].vectorMasks = [...currentMasks, newMask];
              return editor;
            },
            patch: (data) => {
              patches[layerId] = { ...patches[layerId], ...data };
              return editor;
            },
            reset: () => {
              patches[layerId] = { ...LayerFactory.getBlank() };
              return editor;
            },
            emptyLayer: () => {
              patches[layerId] = {
                ...patches[layerId],
                src: LayerFactory.TRANSPARENT_PIXEL,
                assetId: 'asset-transparent-pixel',
                vectorMasks: []
              };
              return editor;
            },
            maskLayer: () => {
              const currentLayer = layer;
              if (!currentLayer) return editor;

              const fullMask = LayerFactory.getNewVectorMask(
                asLocalShape({ x: 0, y: 0, w: currentLayer.bounding.w, h: currentLayer.bounding.h }, 'rect'),
                true
              );

              patches[layerId].vectorMasks = [...(patches[layerId].vectorMasks || []), fullMask];
              return editor;
            },
            resetWithBounds: (w, h, cx, cy) => {
              const { rotation, flip, opacity, adjustments, vectorMasks } = LayerFactory.getNewLayer();
              patches[layerId] = {
                ...patches[layerId],
                cx, cy,
                bounding: { w, h },
                visibleShape: asLocalShape({ x: 0, y: 0, w, h }),
                scale: 1, rotation, flip, opacity, adjustments, vectorMasks,
              };
              return editor;
            },
            setOpacity: (opacity) => {
              patches[layerId] = { ...patches[layerId], opacity };
              return editor;
            },
            setVisible: (visible) => {
              patches[layerId] = { ...patches[layerId], visible };
              return editor;
            },

            // --- Bitmap Mask operations ---
            applyBitmapMask: (src, assetId, bounds) => {
              const currentBitmapMasks = patches[layerId].bitmapMasks || layer?.bitmapMasks || [];
              const newMask = LayerFactory.getNewBitmapMask(src, assetId, bounds);
              patches[layerId].bitmapMasks = [...currentBitmapMasks, newMask];
              return editor;
            },
            removeBitmapMask: (maskId) => {
              const currentBitmapMasks = patches[layerId].bitmapMasks || layer?.bitmapMasks || [];
              patches[layerId].bitmapMasks = currentBitmapMasks.filter((m: BitmapMask) => m.id !== maskId);
              return editor;
            },
            updateBitmapMask: (maskId, maskPatch) => {
              const currentBitmapMasks = patches[layerId].bitmapMasks || layer?.bitmapMasks || [];
              patches[layerId].bitmapMasks = currentBitmapMasks.map((m: BitmapMask) =>
                m.id === maskId ? { ...m, ...maskPatch } : m
              );
              return editor;
            }
          };
          return editor;
        }
      };

      // Execute transaction logic
      runner(tx);

      // --- Core Enhancement: Cascade Calculation ---
      const finalPatches: Record<string, Partial<Layer>> = {};

      const layersArray = frame.layers.order.map(id => frame.layers.byId[id]);
      Object.entries(patches).forEach(([layerId, patch]) => {
        const cascade = LayerFactory.getLayerCascadePatches(layersArray, layerId, patch);
        Object.assign(finalPatches, cascade);
      });

      // Summarize and commit
      if (Object.keys(finalPatches).length > 0) {
        actions.batchUpdateLayers(frameId, finalPatches);
      }
    },



    addLayer: (frameId, layer, index) => {
      const expanded = LayerFactory.expandLayers([layer]);
      actions.addLayers(frameId, expanded, index);
    },

    addFrame: (frame, switchFrame = true) => {
      actions.addFrame(frame, switchFrame);
    },

    activate: (frameId, layerId) => {
      if (layerId) {
        const state = getState();
        const frame = state.frames.byId[frameId];
        const layer = frame?.layers.byId[layerId];
        if (layer && !LayerFactory.canLayerBeActivated(layer)) return;
      }
      actions.setActiveLayer(frameId, layerId);
    },

    // Upgraded version: supports passing either a single ID or an array of IDs (multi-selection delete)
    removeLayers: (frameId: string, layerIds: string | string[]) => {
      const state = getState();
      const frame = state.frames.byId[frameId];
      if (!frame) return;

      // 1. Standardize into array, regardless of single or multi selection
      const targetIds = Array.isArray(layerIds) ? layerIds : [layerIds];

      // 2. Collect all selected layers and their respective descendants
      const idsToRemove = new Set<string>(targetIds);
      let previousSize: number;
      do {
        previousSize = idsToRemove.size;
        frame.layers.order.forEach((id) => {
          const l = frame.layers.byId[id];
          if (l.parentId && idsToRemove.has(l.parentId)) {
            idsToRemove.add(l.id);
          }
        });
      } while (idsToRemove.size !== previousSize);

      // 3. Compute focus (uses the index of the first selected layer in multi-delete as the reference frame)
      const firstTargetId = targetIds[0];
      const targetIndex = frame.layers.order.indexOf(firstTargetId);
      const nextLayers = frame.layers.order.map(id => frame.layers.byId[id]).filter((l) => !idsToRemove.has(l.id));

      let nextActiveId = frame.activeLayerId;
      const needsNewSelection =
        idsToRemove.has(frame.activeLayerId || '') ||
        !frame.activeLayerId ||
        !nextLayers.some((l) => l.id === frame.activeLayerId);

      if (needsNewSelection) {
        if (nextLayers.length === 0) {
          nextActiveId = null;
        } else {
          const safeIndex = Math.min(targetIndex, nextLayers.length - 1);
          nextActiveId = nextLayers[safeIndex >= 0 ? safeIndex : 0].id;
        }
      }

      // 4. Dispatch result (Reducer requires no changes as it naturally accepts arrays!)
      actions.removeLayers(frameId, Array.from(idsToRemove), nextActiveId);
    },

    removeFrame: (frameId: string) => {
      const state = getState();

      // 1. BFS to collect all descendant artboard IDs
      const idsToRemove = new Set<string>([frameId]);
      let previousSize: number;
      do {
        previousSize = idsToRemove.size;
        state.frames.order.forEach((id) => {
          const f = state.frames.byId[id];
          if (f.parentId && idsToRemove.has(f.parentId)) {
            idsToRemove.add(f.id);
          }
        });
      } while (idsToRemove.size !== previousSize);

      // 2. Focus migration calculation: if the active artboard is deleted, select the first surviving artboard
      const nextFrames = state.frames.order.map(id => state.frames.byId[id]).filter(f => !idsToRemove.has(f.id));
      let nextActiveFrameId = state.activeFrameId;
      if (idsToRemove.has(state.activeFrameId || '')) {
        nextActiveFrameId = nextFrames.length > 0 ? nextFrames[0].id : null;
      }

      // 3. Dispatch precalculated results to Reducer (Reducer only performs pure state operations + history internal cleanup)
      actions.removeFrame(Array.from(idsToRemove), nextActiveFrameId);
    },

    getTriplet: (frameId, layerId) => {
      const state = getState();
      const frame = state.frames.byId[frameId];
      const layer = frame?.layers.byId[layerId];
      if (!layer || !frame) return null;

      return LayerFactory.getTriplet(layer, frame.layers.order.map(id => frame.layers.byId[id]));
    },
    fragmentToLayerLogical: (frame, layer, selection, nameType) => {
      const localShape = isPolygon(selection)
        ? polygonToShape(geometry.polygon.frameLocalToLayerLocalPolygon(selection, frame, layer))
        : geometry.shape.frameLocalToLayerLocal(selection, frame, layer);
      const intersection = geometry.shape.intersectWithLayer(localShape, layer);

      if (!intersection) return null;

      const { id: _oldId, ...layerData } = layer;
      const newLayer = LayerFactory.getNewLayer({
        ...layerData,
        vectorMasks: layerData.vectorMasks?.filter(m => !m.reserved) || [],
        name: LayerFactory.getNewLayerName(frame.layers.order.map(id => frame.layers.byId[id]), nameType),
        parentId: undefined
      });

      const v = intersection.visibleShape.rect;
      newLayer.bounding = { w: v.w, h: v.h };
      newLayer.visibleShape = { ...intersection.visibleShape };
      newLayer.cx = intersection.center.x;
      newLayer.cy = intersection.center.y;
      newLayer.birthCenter = { cx: newLayer.cx, cy: newLayer.cy }; // 💡 Record birth center to trigger the golden return guide line when dragging fragments

      return { newLayer, localShape };
    },

    resampleLayerPhysical: async (layer, scaleX, scaleY) => {
      try {
        const isUniform = Math.abs(scaleX - scaleY) < 0.001;

        if (isUniform) {
          const totalScaleX = scaleX;
          const totalScaleY = scaleY;
          const targetW = Math.max(1, Math.round(layer.bounding.w * totalScaleX));
          const targetH = Math.max(1, Math.round(layer.bounding.h * totalScaleY));

          let url = layer.src;
          let id = layer.assetId;

          if (layer.src && layer.src !== LayerFactory.TRANSPARENT_PIXEL) {
            const dim = await pixels.decode.dimensions(layer.src);
            const targetSrcW = Math.max(1, Math.round(dim.w * totalScaleX));
            const targetSrcH = Math.max(1, Math.round(dim.h * totalScaleY));

            const newBlob = await pixels.process.resample(layer.src, { targetSize: { w: targetSrcW, h: targetSrcH } });
            id = await assets.register(newBlob);
            url = assets.getURL(id)!;

            await pixels.decode.htmlImage(url);
          }

          const updatedVisibleShape = layer.visibleShape ? {
            ...layer.visibleShape,
            rect: asLocalRect({
              x: layer.visibleShape.rect.x * totalScaleX,
              y: layer.visibleShape.rect.y * totalScaleY,
              w: layer.visibleShape.rect.w * totalScaleX,
              h: layer.visibleShape.rect.h * totalScaleY
            })
          } : undefined;

          const updatedMasks = layer.vectorMasks?.map((mask: VectorMask) => ({
            ...mask,
            shape: {
              ...mask.shape,
              rect: asLocalRect({
                x: mask.shape.rect.x * totalScaleX,
                y: mask.shape.rect.y * totalScaleY,
                w: mask.shape.rect.w * totalScaleX,
                h: mask.shape.rect.h * totalScaleY
              })
            }
          }));

          const patch: Partial<Layer> = {
            src: url,
            assetId: id,
            cx: layer.cx * scaleX,
            cy: layer.cy * scaleY,
            bounding: { w: targetW, h: targetH },
            scale: 1,
            ...(updatedVisibleShape && { visibleShape: updatedVisibleShape }),
            ...(updatedMasks && { vectorMasks: updatedMasks })
          };

          return { newUrl: url, newAssetId: id || '', patch };
        } else {
          const M = geometry.transform.getLayerWorldMatrix(layer);
          const w = layer.bounding.w;
          const h = layer.bounding.h;
          const corners = [
            { x: 0, y: 0 }, { x: w, y: 0 }, { x: 0, y: h }, { x: w, y: h }
          ].map(p => M.apply(p));

          const minX = Math.min(...corners.map(p => p.x));
          const maxX = Math.max(...corners.map(p => p.x));
          const minY = Math.min(...corners.map(p => p.y));
          const maxY = Math.max(...corners.map(p => p.y));

          const aabb = { x: minX, y: minY, w: maxX - minX, h: maxY - minY };

          let finalUrl = layer.src;
          let finalId = layer.assetId;
          const targetW = Math.max(1, Math.round(aabb.w * scaleX));
          const targetH = Math.max(1, Math.round(aabb.h * scaleY));

          if (layer.src && layer.src !== LayerFactory.TRANSPARENT_PIXEL) {
            const bakedBlobResult = await pixels.worker.mergeLayersWithShape([layer], asWorldShape(aabb, 'rect'));
            const bakedAsset = await pixels.worker.asAsset(Promise.resolve(bakedBlobResult));

            const newBlob = await pixels.process.resample(bakedAsset.url, { targetSize: { w: targetW, h: targetH } });
            finalId = await assets.register(newBlob);
            finalUrl = assets.getURL(finalId)!;

            await pixels.decode.htmlImage(finalUrl);
          }

          const newCx = (aabb.x + aabb.w / 2) * scaleX;
          const newCy = (aabb.y + aabb.h / 2) * scaleY;

          const patch: Partial<Layer> = {
            src: finalUrl,
            assetId: finalId,
            cx: newCx,
            cy: newCy,
            bounding: { w: targetW, h: targetH },
            scale: 1,
            rotation: 0,
            flip: { h: false, v: false },
            visibleShape: asLocalShape({ x: 0, y: 0, w: targetW, h: targetH }),
            vectorMasks: []
          };

          return { newUrl: finalUrl, newAssetId: finalId || '', patch };
        }
      } catch (err) {
        console.error('[LayerService] Resample physical failed for layer:', layer.id, err);
        return null;
      }
    },

    fragmentToExistLayer: (frame, sourceLayer, targetLayer, selection) => {
      const localShape = isPolygon(selection)
        ? polygonToShape(geometry.polygon.frameLocalToLayerLocalPolygon(selection, frame, sourceLayer))
        : geometry.shape.frameLocalToLayerLocal(selection, frame, sourceLayer);
      const intersection = geometry.shape.intersectWithLayer(localShape, sourceLayer);

      if (!intersection) return null;

      const v = intersection.visibleShape.rect;

      const updatedLayer = {
        ...targetLayer,
        src: sourceLayer.src,
        assetId: sourceLayer.assetId,
        cx: intersection.center.x,
        cy: intersection.center.y,
        scale: 1,
        rotation: sourceLayer.rotation,
        flip: { ...sourceLayer.flip },
        bounding: { w: v.w, h: v.h },
        visibleShape: { ...intersection.visibleShape },
        interactive: true,
        opacity: 1,
        visible: true
      };

      return { updatedLayer, localShape };
    },

    fragmentToLayerPhysical: async (frame, layer, selection, nameType) => {
      const localShape = isPolygon(selection)
        ? polygonToShape(geometry.polygon.frameLocalToLayerLocalPolygon(selection, frame, layer))
        : geometry.shape.frameLocalToLayerLocal(selection, frame, layer);
      const intersection = geometry.shape.intersectWithLayer(localShape, layer);
      if (!intersection) return null;

      // For pixel rasterization, convert selection to world-space shape
      const frameLocalShape = isPolygon(selection) ? polygonToShape(selection) : selection;
      const worldSelection = geometry.shape.localToWorldShape(frameLocalShape, frame);
      const targetW = Math.round(worldSelection.rect.w);
      const targetH = Math.round(worldSelection.rect.h);

      const assetResult = await pixels.worker.asAsset(
        pixels.worker.mergeLayersWithShape([layer], worldSelection)
      );

      const trimmedRect = await pixels.decode.contentBounds(assetResult.url);

      if (trimmedRect.w <= 0 || trimmedRect.h <= 0) return null;

      const isFull = trimmedRect.x === 0 && trimmedRect.y === 0 && trimmedRect.w === targetW && trimmedRect.h === targetH;
      const finalAsset = isFull
        ? { id: assetResult.id, url: assetResult.url }
        : await pixels.worker.asAsset(pixels.worker.cloneRegion(assetResult.id, trimmedRect));

      const cx = worldSelection.rect.x + (trimmedRect.x + trimmedRect.w / 2);
      const cy = worldSelection.rect.y + (trimmedRect.y + trimmedRect.h / 2);

      const { id: _, ...layerData } = layer;
      const newLayer = LayerFactory.getNewLayer({
        ...layerData,
        src: finalAsset.url,
        assetId: finalAsset.id,
        vectorMasks: layerData.vectorMasks?.filter(m => !m.reserved) || [],
        name: LayerFactory.getNewLayerName(frame.layers.order.map(id => frame.layers.byId[id]), nameType),
        parentId: undefined,
        visibleShape: asLocalShape({ x: 0, y: 0, w: trimmedRect.w, h: trimmedRect.h }, worldSelection.type),
        bounding: { w: trimmedRect.w, h: trimmedRect.h },
        cx,
        cy,
        birthCenter: { cx, cy }, // 💡 Record birth center to trigger the golden return guide line when dragging fragments
        scale: 1,
        rotation: 0,
        flip: { h: false, v: false },
        adjustments: { brightness: 100, contrast: 100, saturation: 100, hueRotate: 0, blur: 0 }
      });

      return {
        newLayer,
        localShape,
        url: finalAsset.url
      };
    },
    createLayerFromBlob: async (blob, frame, screenPoint) => {
      const assetId = await assets.register(blob);
      const url = assets.getURL(assetId)!;
      const dim = await pixels.decode.dimensions(url);

      // layer.cx/cy uses the world coordinate system (origin at canvas center), directly using the screenToWorld result
      let cx, cy;
      if (screenPoint) {
        const worldPos = geometry.space.screenToWorld(screenPoint.x, screenPoint.y, frame);
        cx = worldPos.x;
        cy = worldPos.y;
      } else {
        const state = getState();
        const vDim = state.ui.viewportDim;
        const worldCenter = geometry.space.screenToWorld(vDim.w / 2, vDim.h / 2, frame);
        cx = worldCenter.x;
        cy = worldCenter.y;
      }

      const layersArray = frame.layers.order.map(id => frame.layers.byId[id]);
      const smartName = LayerFactory.getNewLayerName(layersArray, 'Pasted');

      return LayerFactory.getNewLayer({
        name: smartName,
        src: url,
        assetId: assetId,
        cx,
        cy,
        bounding: dim,
        visibleShape: asLocalShape({ x: 0, y: 0, w: dim.w, h: dim.h }),
        birthCenter: { cx, cy }
      });
    },
  };
}

export * from './LayerFactory';
