/**
 * OpenGPEX - An Open-source, Web-based Graphics and Photo editor.
 * Copyright (C) 2026 The OpenGPEX Authors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-3.0-only
 */

import { GeometryService, PixelService, AssetService, LayerService, LayerUpdateTx, LayerEditor, asLocalShape, asLocalRect, EditorActions, EditorData, Layer, VectorMask, BitmapMask, isPolygon } from '@opengpex/editor/core/types';
import { polygonToShape } from '@opengpex/editor/core/helpers/path2d';
import { getClipBox } from '@opengpex/editor/core/helpers/selection';
import { LayerFactory } from './LayerFactory';

/** Business convention: ID feature of hole masks generated by peeling */
// const MASK_ID_PEEL_HOLE = 'mask-peel-hole';

export function createLayerService(
  geometry: GeometryService,
  pixels: PixelService,
  assets: AssetService,
  actions: EditorActions,
  getState: () => EditorData
): LayerService {
  return {
    ...LayerFactory,

    updateLayer: (frameId, runner) => {
      const state = getState();
      const frame = state.frames.byId[frameId];
      if (!frame) return;

      const patches: Record<string, Partial<Layer>> = {};

      const tx: LayerUpdateTx = {
        edit: (layerId) => {
          const layer = frame.layers.byId[layerId];
          if (!layer) {
            console.warn(`[LayerTx] Layer ${layerId} not found in frame ${frameId}`);
          }

          // 🌟 Initialize vectorMasks in draft to avoid duplicate fallbacks later
          if (!patches[layerId]) {
            patches[layerId] = {};
          }
          if (patches[layerId].vectorMasks === undefined) {
            patches[layerId].vectorMasks = layer?.vectorMasks || [];
          }

          const editor: LayerEditor = {
            setAsset: (asset) => {
              patches[layerId] = { ...patches[layerId], src: asset.url, assetId: asset.id };
              return editor;
            },
            setShape: (shape) => {
              patches[layerId] = { ...patches[layerId], ...shape };
              return editor;
            },
            removeMask: (pattern) => {
              const currentMasks = patches[layerId].vectorMasks || [];
              const newMasks = currentMasks.filter((m: VectorMask) => !m.id.includes(pattern));
              patches[layerId].vectorMasks = newMasks;
              return editor;
            },
            applyMask: (shape, inverted = false, feather = 0) => {
              const currentMasks = patches[layerId].vectorMasks || [];
              const newMask = LayerFactory.getNewVectorMask(shape, inverted, feather);
              patches[layerId].vectorMasks = [...currentMasks, newMask];
              return editor;
            },
            patch: (data) => {
              patches[layerId] = { ...patches[layerId], ...data };
              return editor;
            },
            reset: () => {
              patches[layerId] = { ...LayerFactory.getBlank() };
              return editor;
            },
            emptyLayer: () => {
              patches[layerId] = {
                ...patches[layerId],
                src: LayerFactory.TRANSPARENT_PIXEL,
                assetId: 'asset-transparent-pixel',
                vectorMasks: []
              };
              return editor;
            },
            maskLayer: () => {
              const currentLayer = layer;
              if (!currentLayer) return editor;

              const fullMask = LayerFactory.getNewVectorMask(
                asLocalShape({ x: 0, y: 0, w: currentLayer.bounding.w, h: currentLayer.bounding.h }, 'rect'),
                true
              );

              patches[layerId].vectorMasks = [...(patches[layerId].vectorMasks || []), fullMask];
              return editor;
            },
            resetWithBounds: (w, h, cx, cy) => {
              const { rotation, flip, opacity, adjustments, vectorMasks } = LayerFactory.getNewLayer();
              patches[layerId] = {
                ...patches[layerId],
                cx, cy,
                bounding: { w, h },
                visibleShape: asLocalShape({ x: 0, y: 0, w, h }),
                scale: 1, rotation, flip, opacity, adjustments, vectorMasks,
              };
              return editor;
            },
            setOpacity: (opacity) => {
              patches[layerId] = { ...patches[layerId], opacity };
              return editor;
            },
            setVisible: (visible) => {
              patches[layerId] = { ...patches[layerId], visible };
              return editor;
            },

            // --- Bitmap Mask operations ---
            applyBitmapMask: (src, assetId, bounds) => {
              const currentBitmapMasks = patches[layerId].bitmapMasks || layer?.bitmapMasks || [];
              const newMask = LayerFactory.getNewBitmapMask(src, assetId, bounds);
              patches[layerId].bitmapMasks = [...currentBitmapMasks, newMask];
              return editor;
            },
            removeBitmapMask: (maskId) => {
              const currentBitmapMasks = patches[layerId].bitmapMasks || layer?.bitmapMasks || [];
              patches[layerId].bitmapMasks = currentBitmapMasks.filter((m: BitmapMask) => m.id !== maskId);
              return editor;
            },
            updateBitmapMask: (maskId, maskPatch) => {
              const currentBitmapMasks = patches[layerId].bitmapMasks || layer?.bitmapMasks || [];
              patches[layerId].bitmapMasks = currentBitmapMasks.map((m: BitmapMask) =>
                m.id === maskId ? { ...m, ...maskPatch } : m
              );
              return editor;
            }
          };
          return editor;
        }
      };

      // Execute transaction logic
      runner(tx);

      // --- Core Enhancement: Cascade Calculation ---
      const finalPatches: Record<string, Partial<Layer>> = {};

      const layersArray = frame.layers.order.map(id => frame.layers.byId[id]);
      Object.entries(patches).forEach(([layerId, patch]) => {
        const cascade = LayerFactory.getLayerCascadePatches(layersArray, layerId, patch);
        Object.assign(finalPatches, cascade);
      });

      // Summarize and commit
      if (Object.keys(finalPatches).length > 0) {
        actions.batchUpdateLayers(frameId, finalPatches);
      }
    },


    addLayer: (frameId, layer, index) => {
      const expanded = LayerFactory.expandLayers([layer]);
      actions.addLayers(frameId, expanded, index);
    },

    addFrame: (frame, switchFrame = true) => {
      actions.addFrame(frame, switchFrame);
    },

    activate: (frameId, layerId) => {
      if (layerId) {
        const state = getState();
        const frame = state.frames.byId[frameId];
        const layer = frame?.layers.byId[layerId];
        if (layer && !LayerFactory.canLayerBeActivated(layer)) return;
      }
      actions.setActiveLayer(frameId, layerId);
    },

    // Upgraded version: supports passing either a single ID or an array of IDs (multi-selection delete)
    removeLayers: (frameId: string, layerIds: string | string[]) => {
      const frame = getState().frames.byId[frameId];
      if (!frame) return;

      const targetIds = Array.isArray(layerIds) ? layerIds : [layerIds];
      const allLayers = frame.layers.order.map(id => frame.layers.byId[id]);
      const idsToRemove = LayerFactory.collectDescendants(targetIds, allLayers);

      // Focus migration: pick nearest host layer if active is being removed
      let nextActiveId: string | null = frame.activeLayerId ?? null;
      if (!nextActiveId || idsToRemove.has(nextActiveId)) {
        const candidates = LayerFactory.getHostLayers(allLayers.filter(l => !idsToRemove.has(l.id)));
        const targetIndex = frame.layers.order.indexOf(targetIds[0]);
        const safeIndex = Math.min(targetIndex, candidates.length - 1);
        nextActiveId = candidates[safeIndex >= 0 ? safeIndex : 0]?.id ?? null;
      }

      actions.removeLayers(frameId, Array.from(idsToRemove), nextActiveId);
    },

    removeFrame: (frameId: string) => {
      const state = getState();
      const allFrames = state.frames.order.map(id => state.frames.byId[id]);
      // Map Frame.parentId → hostId so collectDescendants can traverse the trunk→branch tree
      const asHostItems = allFrames.map(f => ({ id: f.id, hostId: f.parentId ?? null }));
      const idsToRemove = LayerFactory.collectDescendants([frameId], asHostItems);

      // Focus migration: pick first surviving frame
      let nextActiveFrameId: string | null = state.activeFrameId ?? null;
      if (nextActiveFrameId && idsToRemove.has(nextActiveFrameId)) {
        nextActiveFrameId = allFrames.find(f => !idsToRemove.has(f.id))?.id ?? null;
      }

      actions.removeFrame(Array.from(idsToRemove), nextActiveFrameId);
    },

    getTriplet: (frameId, layerId) => {
      const state = getState();
      const frame = state.frames.byId[frameId];
      const layer = frame?.layers.byId[layerId];
      if (!layer || !frame) return null;

      return LayerFactory.getTriplet(layer, frame.layers.order.map(id => frame.layers.byId[id]));
    },
    
    fragmentToLayerLogical: (frame, layer, nameType) => {
      const box = getClipBox(frame);
      if (!box) return null;
      const localShape = polygonToShape(geometry.polygon.frameLocalToLayerLocal(box, frame, layer));
      const intersection = geometry.shape.intersectWithLayer(localShape, layer);

      if (!intersection) return null;

      // Guard: path∩path case — when the layer has a non-rect visibleShape AND the selection
      // is also a path (irregular), intersectWithLayer cannot compute the true geometric
      // intersection (would need polygon-clipping). The result only carries the selection's
      // path, losing the layer's constraint. Fall back to physical (composite + trim).
      //
      // NOTE: rect∩path is now handled correctly by Sutherland-Hodgman clipping in
      // intersectWithLayer, which produces a properly clipped pathData. No fallback needed.
      if (layer.visibleShape && layer.visibleShape.type !== 'rect' && localShape.type !== 'rect') {
        return null;
      }

      const { id: _oldId, ...layerData } = layer;
      const newLayer = LayerFactory.getNewLayer({
        ...layerData,
        vectorMasks: layerData.vectorMasks?.filter(m => !m.reserved) || [],
        name: LayerFactory.getNewLayerName(frame.layers.order.map(id => frame.layers.byId[id]), nameType),
        hostId: undefined
      });

      const v = intersection.visibleShape.rect;
      newLayer.bounding = { w: v.w, h: v.h };
      newLayer.visibleShape = { ...intersection.visibleShape };
      // Correctly compute (cx, cy) accounting for layer orientation (rotation/flip).
      // The simplified formula (cx = center.x - vx) only holds when orientation is identity.
      const pose = geometry.transform.computeFragmentCenter(intersection.center, { x: v.x, y: v.y }, layer.rotation, layer.flip);
      newLayer.cx = pose.x;
      newLayer.cy = pose.y;
      newLayer.birthCenter = { cx: newLayer.cx, cy: newLayer.cy }; // 💡 Record birth center to trigger the golden return guide line when dragging fragments

      // Mark as logical (non-physical) layer: src references the original image,
      // visibleShape provides the clip mask. Default is true (physical pixels).
      newLayer.metadata = { ...newLayer.metadata, physicalPixels: false };

      // Record the source clip tool so refocus can restore the correct tool slot
      if (frame.latestClipTool) {
        newLayer.metadata = { ...newLayer.metadata, clipTool: frame.latestClipTool };
      }

      return { newLayer, localShape };
    },

    fragmentToLayerPhysical: async (frame, layer, nameType) => {
      const box = getClipBox(frame);
      if (!box) return null;
      const localShape = polygonToShape(geometry.polygon.frameLocalToLayerLocal(box, frame, layer));
      const intersection = geometry.shape.intersectWithLayer(localShape, layer);
      if (!intersection) return null;

      // For pixel rasterization, use frame-local shape as composite ROI
      const frameLocalShape = polygonToShape(box);
      const worldSelection = geometry.shape.localToWorldShape(frameLocalShape, frame);

      // ── Composite + trim in memory (no intermediate asset registration) ────
      const { result: fragResult } = await pixels.render.compositeLayers([layer], frame, frameLocalShape);
      const trimResult = await fragResult.trimmed();
      if (!trimResult) return null; // Entirely transparent — no content in selection

      const { result: trimmedResult, offset } = trimResult;
      const trimW = trimmedResult.bounds.w;
      const trimH = trimmedResult.bounds.h;
      const { id: assetId, url: assetUrl } = await trimmedResult.toAsset();
      const cx = worldSelection.rect.x + (offset.x + trimW / 2);
      const cy = worldSelection.rect.y + (offset.y + trimH / 2);

      const { id: _, ...layerData } = layer;
      const newLayer = LayerFactory.getNewLayer({
        ...layerData,
        src: assetUrl,
        assetId: assetId,
        vectorMasks: layerData.vectorMasks?.filter(m => !m.reserved) || [],
        name: LayerFactory.getNewLayerName(frame.layers.order.map(id => frame.layers.byId[id]), nameType),
        hostId: undefined,
        visibleShape: asLocalShape({ x: 0, y: 0, w: trimW, h: trimH }, worldSelection.type),
        bounding: { w: trimW, h: trimH },
        cx,
        cy,
        birthCenter: { cx, cy }, // 💡 Record birth center to trigger the golden return guide line when dragging fragments
        scale: 1,
        rotation: 0,
        flip: { h: false, v: false },
        adjustments: { brightness: 100, contrast: 100, saturation: 100, hueRotate: 0, blur: 0 }
      });

      return {
        newLayer,
        localShape,
        url: assetUrl
      };
    },
    
    resampleLayerPhysical: async (layer, scaleX, scaleY, frame) => {
      try {
        const hasContent = layer.src && layer.src !== LayerFactory.TRANSPARENT_PIXEL;
        const isUniform = Math.abs(scaleX - scaleY) < 0.001;

        if (isUniform) {
          // ── Uniform scale: resample source directly, preserve masks/visibleShape ──
          const targetW = Math.max(1, Math.round(layer.bounding.w * scaleX));
          const targetH = Math.max(1, Math.round(layer.bounding.h * scaleY));

          let id = layer.assetId;
          let url = layer.src;

          if (hasContent) {
            // Source pixel dims === layer.bounding (invariant maintained by prior resamples)
            const result = await pixels.image.resample(layer.src, {
              targetSize: { w: targetW, h: targetH },
            });
            ({ id, url } = await result.toAsset());
          }

          const scaleRect = (r: { x: number; y: number; w: number; h: number }) =>
            asLocalRect({ x: r.x * scaleX, y: r.y * scaleY, w: r.w * scaleX, h: r.h * scaleY });

          const patch: Partial<Layer> = {
            src: url, assetId: id,
            cx: layer.cx * scaleX,
            cy: layer.cy * scaleY,
            bounding: { w: targetW, h: targetH },
            scale: 1,
            ...(layer.visibleShape && { visibleShape: { ...layer.visibleShape, rect: scaleRect(layer.visibleShape.rect) } }),
            ...(layer.vectorMasks && {
              vectorMasks: layer.vectorMasks.map((m: VectorMask) => ({
                ...m, shape: { ...m.shape, rect: scaleRect(m.shape.rect) },
              })),
            }),
          };

          return { newUrl: url, newAssetId: id || '', patch };
        } else {
          // ── Non-uniform scale: bake (flatten) then resample, reset orientation ──
          const aabb = geometry.space.getLayerBoundingBox(layer);
          const targetW = Math.max(1, Math.round(aabb.w * scaleX));
          const targetH = Math.max(1, Math.round(aabb.h * scaleY));

          let id = layer.assetId;
          let url = layer.src;

          if (hasContent) {
            const { result } = await pixels.render.compositeResizedLayers([layer], frame, { w: targetW, h: targetH });
            ({ id, url } = await result.toAsset());
          }

          const patch: Partial<Layer> = {
            src: url, assetId: id,
            cx: (aabb.x + aabb.w / 2) * scaleX,
            cy: (aabb.y + aabb.h / 2) * scaleY,
            bounding: { w: targetW, h: targetH },
            scale: 1, rotation: 0, flip: { h: false, v: false },
            visibleShape: asLocalShape({ x: 0, y: 0, w: targetW, h: targetH }),
            vectorMasks: [],
          };

          return { newUrl: url, newAssetId: id || '', patch };
        }
      } catch (err) {
        console.error('[LayerService] Resample physical failed for layer:', layer.id, err);
        return null;
      }
    },

    fragmentToExistLayer: (frame, sourceLayer, targetLayer, selection) => {
      const localShape = isPolygon(selection)
        ? polygonToShape(geometry.polygon.frameLocalToLayerLocal(selection, frame, sourceLayer))
        : geometry.shape.frameLocalToLayerLocal(selection, frame, sourceLayer);
      const intersection = geometry.shape.intersectWithLayer(localShape, sourceLayer);

      if (!intersection) return null;

      const v = intersection.visibleShape.rect;
      // Correctly compute (cx, cy) accounting for source layer orientation (rotation/flip).
      const pose = geometry.transform.computeFragmentCenter(intersection.center, { x: v.x, y: v.y }, sourceLayer.rotation, sourceLayer.flip);

      const updatedLayer = {
        ...targetLayer,
        src: sourceLayer.src,
        assetId: sourceLayer.assetId,
        cx: pose.x,
        cy: pose.y,
        scale: 1,
        rotation: sourceLayer.rotation,
        flip: { ...sourceLayer.flip },
        bounding: { w: v.w, h: v.h },
        visibleShape: { ...intersection.visibleShape },
        interactive: true,
        opacity: 1,
        visible: true,
        // Propagate non-destructive adjustment state so the fragment renders
        // identically to the source layer (fix: peel losing adjustments).
        adjustments: sourceLayer.adjustments,
        curves: sourceLayer.curves,
        levels: sourceLayer.levels,
        channelMix: sourceLayer.channelMix,
        colorBalance: sourceLayer.colorBalance,
      };

      return { updatedLayer, localShape };
    },

    createLayerFromBlob: async (blob, frame, screenPoint) => {
      const bmp = await createImageBitmap(blob);
      const dim = { w: bmp.width, h: bmp.height };
      bmp.close();
      const { id: assetId, url } = await assets.register(blob, dim);

      // layer.cx/cy uses the world coordinate system (origin at canvas center), directly using the screenToWorld result
      let cx, cy;
      if (screenPoint) {
        const worldPos = geometry.space.screenToWorld(screenPoint.x, screenPoint.y, frame);
        cx = worldPos.x;
        cy = worldPos.y;
      } else {
        const state = getState();
        const vDim = state.ui.viewportDim;
        const worldCenter = geometry.space.screenToWorld(vDim.w / 2, vDim.h / 2, frame);
        cx = worldCenter.x;
        cy = worldCenter.y;
      }

      const layersArray = frame.layers.order.map(id => frame.layers.byId[id]);
      const smartName = LayerFactory.getNewLayerName(layersArray, 'Pasted');

      return LayerFactory.getNewLayer({
        name: smartName,
        src: url,
        assetId: assetId,
        cx,
        cy,
        bounding: dim,
        visibleShape: asLocalShape({ x: 0, y: 0, w: dim.w, h: dim.h }),
        birthCenter: { cx, cy }
      });
    },
  };
}

export * from './LayerFactory';
