/**
 * OpenGPEX - An Open-source, Web-based Graphics and Photo editor.
 * Copyright (C) 2026 The OpenGPEX Authors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-3.0-only
 */

'use client';

import React, { useRef } from 'react';
import { useEditorState, useOverlayRotationSync } from '@opengpex/editor/core/context';
import { useMarkerOverlayState, useMarkerPreviewFastSync, useMarkerToolLifecycle, useMarkerSelectionFastSync } from './hooks';

// ─── MarkerOverlayMain ───────────────────────────────────────────────────────────

/**
 * MarkerOverlayMain: SVG overlay for the marker tool.
 *
 * Renders in STAGE_OVERLAY (screen-space, above the canvas): a real-time SVG
 * drag preview during marker creation. The selected-marker highlight + resize
 * handles are provided by the shared LayerOverlay (a vector layer is a normal
 * hit-testable layer), so this component only owns the drawing preview.
 *
 * The preview SVG content is generated by core `markerToSvg` (see hooks.ts),
 * keeping the on-canvas preview pixel-identical to the rasterized output.
 *
 * Cursor feedback + Escape handling live in `useMarkerToolLifecycle`, which is
 * called unconditionally (before the early return) so its effects can gate on
 * `isMarkerMode` and clean up on tool switch — never violating hook ordering.
 */
export const MarkerOverlayMain = React.memo(function MarkerOverlayMain() {
  const { isMarkerMode } = useMarkerOverlayState();

  // Cursor + Escape lifecycle (self-gated on isMarkerMode; must run every render).
  useMarkerToolLifecycle(isMarkerMode);

  if (!isMarkerMode) return null;
  return (
    <>
      <MarkerDrawPreview />
      <MarkerSelectionBox />
    </>
  );
});

// ─── MarkerDrawPreview ─────────────────────────────────────────────────────────

/**
 * MarkerDrawPreview: camera-following SVG surface for the drag preview.
 *
 * The container div carries the camera transform (translate + scale) so the
 * inner SVG can draw in canvas-local coordinates. The `<g>` inner content is
 * imperatively updated by useMarkerPreviewFastSync (dirty-checked, 60fps),
 * mirroring BrushOverlay's StrokePreview pattern.
 */
const MarkerDrawPreview = React.memo(function MarkerDrawPreview() {
  const containerRef = useRef<HTMLDivElement>(null);
  const groupRef = useRef<SVGGElement>(null);
  const { activeFrame } = useEditorState();

  useMarkerPreviewFastSync(containerRef, groupRef);

  if (!activeFrame) return null;
  const { w, h } = activeFrame.canvas;

  return (
    <div
      ref={containerRef}
      className="absolute top-0 left-0 pointer-events-none"
      style={{
        transformOrigin: '0 0',
        willChange: 'transform',
      }}
    >
      <svg
        width={w}
        height={h}
        viewBox={`0 0 ${w} ${h}`}
        className="block overflow-visible"
        style={{ width: `${w}px`, height: `${h}px` }}
      >
        <g ref={groupRef} />
      </svg>
    </div>
  );
});

// ─── MarkerSelectionBox ────────────────────────────────────────────────────────

/** Screen-space size (px) of each resize handle dot, constant across zoom. */
const HANDLE_SIZE = 10;

/**
 * The 8 resize handles: 4 corners + 4 edge midpoints.
 *
 * `angle` is the handle's outward normal in the layer's LOCAL space, measured in
 * screen convention (0° = +x / east, growing clockwise because screen +y points
 * down). It is used to pick a rotation-correct cursor: CSS cursors are not
 * affected by CSS `transform`, so a rotated selection box would otherwise keep
 * showing the unrotated (canvas-axis) arrows.
 */
const MARKER_HANDLES = [
  { h: 'nw', angle: 225, style: { top: 0, left: 0 } },
  { h: 'ne', angle: 315, style: { top: 0, left: '100%' } },
  { h: 'sw', angle: 135, style: { top: '100%', left: 0 } },
  { h: 'se', angle: 45, style: { top: '100%', left: '100%' } },
  { h: 'n', angle: 270, style: { top: 0, left: '50%' } },
  { h: 's', angle: 90, style: { top: '100%', left: '50%' } },
  { h: 'w', angle: 180, style: { top: '50%', left: 0 } },
  { h: 'e', angle: 0, style: { top: '50%', left: '100%' } },
] as const;

/**
 * Map an on-screen direction (degrees) to the nearest of the 4 resize cursors.
 *
 * Cursors are bidirectional, so the direction is folded into [0,180) and then
 * bucketed every 45°: e/w → `ew-resize`, ne/sw → `nesw-resize`,
 * n/s → `ns-resize`, nw/se → `nwse-resize`.
 */
function cursorForAngle(angleDeg: number): string {
  const a = ((angleDeg % 180) + 180) % 180;
  const bucket = Math.round(a / 45) % 4;
  switch (bucket) {
    case 0: return 'ew-resize';
    case 1: return 'nwse-resize';   // pointing down-right (screen +y is down)
    case 2: return 'ns-resize';
    default: return 'nesw-resize';  // pointing up-right
  }
}

/**
 * Resolve each handle's cursor for the layer's current pose.
 *
 * The selection box is drawn through the layer's full world matrix (see
 * `useMarkerSelectionFastSync`), so after a canvas Rotate Left/Right the box
 * self-rotates — but CSS `cursor` keywords ignore `transform`. We therefore
 * rotate the handle's local normal by `layer.rotation` (mirroring flips first,
 * matching the renderer's R × F convention) and pick the matching cursor.
 */
function resolveHandleCursor(
  angle: number,
  rotation: number,
  flip: { h: boolean; v: boolean } | undefined
): string {
  // Mirror the direction vector before rotating (F then R, as in getOrientationMatrix).
  const rad = (angle * Math.PI) / 180;
  let dx = Math.cos(rad);
  let dy = Math.sin(rad);
  if (flip?.h) dx = -dx;
  if (flip?.v) dy = -dy;

  const screenAngle = (Math.atan2(dy, dx) * 180) / Math.PI + rotation;
  return cursorForAngle(screenAngle);
}


/**
 * MarkerSelectionBox: outline + 8 resize handles over the active marker layer.
 *
 * A screen-space div (not camera-transformed): `useMarkerSelectionFastSync`
 * writes its left/top/width/height every frame from the fast-track-merged layer
 * bounds, so it tracks camera pan/zoom and live move/resize. Handles carry
 * `data-marker-handle=<dir>` which MarkerResizeHandler's `test` detects; they
 * are `pointer-events-auto` while the outline stays non-interactive so it never
 * blocks move/draw on the shape body.
 */
const MarkerSelectionBox = React.memo(function MarkerSelectionBox() {
  const { activeFrame, activeLayer } = useEditorState();
  const containerRef = useRef<HTMLDivElement>(null);
  const boxRef = useRef<HTMLDivElement>(null);

  const isMarkerLayer = !!(activeLayer && activeLayer.type === 'vector' && activeLayer.markerData);
  const layerId = isMarkerLayer ? activeLayer!.id : null;

  // Rotate the whole overlay container with the canvas (counter-animation
  // protocol), same as ClipOverlay/LayerOverlay. The inner box stays axis-aligned
  // in this rotated container, so its resize handles keep working and the box
  // follows canvas rotation WITH a smooth tween (not a hard jump).
  useOverlayRotationSync(containerRef, activeFrame);
  useMarkerSelectionFastSync(boxRef, layerId);

  if (!activeFrame || !layerId) return null;

  return (
    <div ref={containerRef} className="absolute inset-0 pointer-events-none overflow-visible">
      <div
        ref={boxRef}
        className="absolute top-0 left-0 pointer-events-none"
        style={{ display: 'none', transformOrigin: '0 0', willChange: 'transform, width, height' }}
      >
        {/* Selection outline (1px, non-interactive). */}
        <div className="absolute -inset-[1px] border border-indigo-500/80" />

        {/* Resize handles (interactive dots). */}
        {MARKER_HANDLES.map(({ h, angle, style }) => (
          <div
            key={h}
            data-marker-handle={h}
            className="absolute rounded-full bg-white border border-indigo-500 shadow-sm pointer-events-auto hover:scale-125 transition-transform duration-150"
            style={{
              width: `${HANDLE_SIZE}px`,
              height: `${HANDLE_SIZE}px`,
              cursor: resolveHandleCursor(angle, activeLayer?.rotation ?? 0, activeLayer?.flip),
              transform: 'translate(-50%, -50%)',
              ...style,
            }}
          />
        ))}
      </div>
    </div>
  );
});
