/**
 * OpenGPEX - An Open-source, Web-based Graphics and Photo editor.
 * Copyright (C) 2026 The OpenGPEX Authors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-3.0-only
 */

'use client';

import React, { useRef } from 'react';
import { useEditorState, useOverlayRotationSync } from '@opengpex/editor/core/context';
import { TransformGizmo } from '@opengpex/editor/widgets/TransformGizmo';
import { useMarkerOverlayState, useMarkerPreviewFastSync, useMarkerToolLifecycle, useMarkerSelectionFastSync } from './hooks';

// ─── MarkerOverlayMain ───────────────────────────────────────────────────────────

/**
 * MarkerOverlayMain: SVG overlay for the marker tool.
 *
 * Renders in STAGE_OVERLAY (screen-space, above the canvas): a real-time SVG
 * drag preview during marker creation. The selected-marker highlight + resize
 * handles are provided by the shared LayerOverlay (a vector layer is a normal
 * hit-testable layer), so this component only owns the drawing preview.
 *
 * The preview SVG content is generated by core `markerToSvg` (see hooks.ts),
 * keeping the on-canvas preview pixel-identical to the rasterized output.
 *
 * Cursor feedback + Escape handling live in `useMarkerToolLifecycle`, which is
 * called unconditionally (before the early return) so its effects can gate on
 * `isMarkerMode` and clean up on tool switch — never violating hook ordering.
 */
export const MarkerOverlayMain = React.memo(function MarkerOverlayMain() {
  const { isMarkerMode } = useMarkerOverlayState();

  // Cursor + Escape lifecycle (self-gated on isMarkerMode; must run every render).
  useMarkerToolLifecycle(isMarkerMode);

  if (!isMarkerMode) return null;
  return (
    <>
      <MarkerDrawPreview />
      <MarkerSelectionBox />
    </>
  );
});

// ─── MarkerDrawPreview ─────────────────────────────────────────────────────────

/**
 * MarkerDrawPreview: camera-following SVG surface for the drag preview.
 *
 * The container div carries the camera transform (translate + scale) so the
 * inner SVG can draw in canvas-local coordinates. The `<g>` inner content is
 * imperatively updated by useMarkerPreviewFastSync (dirty-checked, 60fps),
 * mirroring BrushOverlay's StrokePreview pattern.
 */
const MarkerDrawPreview = React.memo(function MarkerDrawPreview() {
  const containerRef = useRef<HTMLDivElement>(null);
  const groupRef = useRef<SVGGElement>(null);
  const { activeFrame } = useEditorState();

  useMarkerPreviewFastSync(containerRef, groupRef);

  if (!activeFrame) return null;
  const { w, h } = activeFrame.canvas;

  return (
    <div
      ref={containerRef}
      className="absolute top-0 left-0 pointer-events-none"
      style={{
        transformOrigin: '0 0',
        willChange: 'transform',
      }}
    >
      <svg
        width={w}
        height={h}
        viewBox={`0 0 ${w} ${h}`}
        className="block overflow-visible"
        style={{ width: `${w}px`, height: `${h}px` }}
      >
        <g ref={groupRef} />
      </svg>
    </div>
  );
});

// ─── MarkerSelectionBox ────────────────────────────────────────────────────────

/** Screen-space size (px) of each resize handle dot, constant across zoom. */
const HANDLE_SIZE = 10;

/**
 * MarkerSelectionBox: outline + 8 resize handles over the active marker layer.
 *
 * A screen-space div (not camera-transformed): `useMarkerSelectionFastSync`
 * writes its left/top/width/height every frame from the fast-track-merged layer
 * bounds, so it tracks camera pan/zoom and live move/resize. The shared
 * `<TransformGizmo>` renders the outline + handles; handles carry
 * `data-gizmo-handle=<dir>` which MarkerResizeHandler's `test` detects; they
 * are `pointer-events-auto` while the outline stays non-interactive so it never
 * blocks move/draw on the shape body.
 */
const MarkerSelectionBox = React.memo(function MarkerSelectionBox() {
  const { activeFrame, activeLayer } = useEditorState();
  const containerRef = useRef<HTMLDivElement>(null);
  const boxRef = useRef<HTMLDivElement>(null);

  const isMarkerLayer = !!(activeLayer && activeLayer.type === 'vector' && activeLayer.markerData);
  const layerId = isMarkerLayer ? activeLayer!.id : null;

  // Rotate the whole overlay container with the canvas (counter-animation
  // protocol), same as ClipOverlay/LayerOverlay. The inner box stays axis-aligned
  // in this rotated container, so its resize handles keep working and the box
  // follows canvas rotation WITH a smooth tween (not a hard jump).
  useOverlayRotationSync(containerRef, activeFrame);
  useMarkerSelectionFastSync(boxRef, layerId);

  if (!activeFrame || !layerId) return null;

  return (
    <div ref={containerRef} className="absolute inset-0 pointer-events-none overflow-visible">
      <div
        ref={boxRef}
        className="absolute top-0 left-0 pointer-events-none"
        style={{ display: 'none', transformOrigin: '0 0', willChange: 'transform, width, height' }}
      >
        <TransformGizmo
          rotation={activeLayer?.rotation ?? 0}
          flip={activeLayer?.flip}
          handleSizePx={HANDLE_SIZE}
          handleClassName="border border-indigo-500"
          showOutline
          outlineClassName="border-indigo-500/80"
        />
      </div>
    </div>
  );
});

